config/routes.rb
Rails.application.routes.draw do
  # redirect herokuapp (in production only)
  # if Rails.env.production? && !ENV.fetch('HOSTNAME').ends_with?('herokuapp.com')
  #   constraints(host: "#{ENV.fetch('HEROKU_APP_NAME') { 'preserve-prod' }}.herokuapp.com") do
  #     get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
  #     get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  #   end
  # end

  # Partner subdomains
  constraints(->(req){ req.subdomain.present? && Subdomains::Partner.matches?(req) }) do
    get '/', to: 'partners#index'
    get :search, to: 'partners#search', constraints: { format: :js }, as: :partner_search
    get :tos, to: 'partners#tos', as: :partner_tos
    get :faq, to: 'partners#faq', as: :partner_faq

    devise_scope :seller_user do
      get '/comerciante/registo', to: 'seller_users/partner_registrations#new', as: :new_partner_signup
      post '/comerciante', to: 'seller_users/partner_registrations#create', as: :partner_signup
    end

    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  # Other subdomains are redirected
  constraints(->(req){ req.host != ENV['HOSTNAME'] &&
                       req.subdomain.present? &&
                       !req.subdomain.in?(Subdomains::Partner.subdomains)}) do
    get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  ### Fix some shared URLs that are 404s
    get '/Compre', to: redirect('/')
    get '/.', to: redirect('/')
    get '/*', to: redirect('/')
  ###

  constraints(host: ENV['HOSTNAME']) do
    root to: 'home#index'

    resources :places, only: [:index, :show]
    resources :vouchers, only: [:create, :show] do
      resources :payments, only: [:new, :create]

      get '/obrigado', to: 'payments#done', as: :thank_you, on: :member
    end

    get '/tos', to: 'home#tos', as: :tos
    get '/tos_mbway', to: 'home#tos_mbway', as: :tos_mbway
    get '/privacy', to: 'home#privacy', as: :privacy

    # devise_for :seller_users,
    #           path: 'comerciante',
    #           controllers: { registrations: 'seller_users/registrations'},
    #           path_names: { sign_up: 'registo' }

    namespace :seller do
      resource :account, only: [:show] do
        put :accept_new_terms
        get :republish, on: :member
      end
      resources :places, except: [:index, :destroy] do
        patch :publish, on: :member
      end
      resources :vouchers, only: [:index, :update] do
        get :redeem, on: :member
      end
    end

    get '/comerciante/bem-vindo', to: 'places#register_success', as: :register_success

    namespace :webhooks do
      get 'payment/eupago', to:'eu_pago#webhook'
    end

    devise_for :admin_users, path: 'admin'

    namespace :admin do
      resources :admin_users
      resources :categories
      resources :csv_imports, except: [:edit, :update]
      resources :payment_notifications, only: [:index, :show]
      resources :sellers
      resources :partners
      resources :partnerships
      resources :partner_identifiers, only: [:index, :show]
      resources :places do
        member do
          patch :publish
          patch :unpublish
        end
      end
      resources :seller_users
      resources :vouchers do
        patch :resend, on: :member
        patch :mark_refunded, on: :member
      end

      get 'stats', to: 'stats#index', as: :stats
      get 'stats/vouchers', to: 'stats#vouchers', as: :voucher_stats
      get 'stats/sellers', to: 'stats#sellers', as: :seller_stats
      root to: "stats#index"
    end
  end

  authenticate :admin_user do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/seller.rb
# frozen_string_literal: true
class Seller < ApplicationRecord
  belongs_to :seller_user
  has_many :places, dependent: :restrict_with_exception
  has_many :vouchers, through: :places

  validates :vat_id, :contact_name, :company_name, presence: true

  before_validation :sanitize_vat_id
  before_validation :normalize_iban
  before_validation :normalize_vat_id

  def to_s
    "Seller ##{id}: #{company_name}"
  end

  private

  def sanitize_vat_id
    vat_id.tr!(' ', '')
  end

  def normalize_iban
    self.iban = Ibandit::IBAN.new(iban).to_s(:formatted) if iban.present?
  end

  def normalize_vat_id
    self.vat_id = vat_id.sub(/PT/i, '')
  end
end

app/controllers/admin/sellers_controller.rb
# frozen_string_literal: true
module Admin
  class SellersController < Admin::ResourcefulController

    def index_columns
      [
        { attr: :id, label: 'ID', sort: :id },
        { attr: :company_name, label: 'Company Name', sort: :company_name },
        { attr: :vat_id, label: 'VAT ID', sort: :vat_id },
        { attr: :payment_api_key, label: 'Payment API Key', sort: :payment_api_key },
        { attr: :created_at, label: 'Created At', sort: :created_at },
        { attr: :updated_at, label: 'Updated At', sort: :updated_at }
      ]
    end

    protected

    def permitted_params
      super.permit!
    end
  end
end

app/controllers/seller/accounts_controller.rb
# frozen_string_literal: true
class Seller::AccountsController < Seller::BaseController
  skip_before_action :authenticate_seller_user!, only: [:republish]
  before_action :load_signin_token, only: [:republish]

  def show
    @seller = current_seller_user.seller
  end

  def accept_new_terms
    current_seller_user.accept_tos!
    redirect_to request.referrer
  end

  def republish
    @seller = current_seller_user.seller
    errors = []
    # Only republish places that were previously published
    to_republish = @seller.places.where(published: false).where.not(published_at: nil)

    redirect_to(seller_account_path) and return if to_republish.empty?

    to_republish.each do |place|

      if place.can_publish?
        place.update(published: true, published_at: Time.now)
      else
        errors << place
      end
    end

    if errors.any?
      flash[:alert] = "Não foi possivel publicar: #{errors.map(&:name).join(', ')}.\nPor favor contacte-nos.".html_safe
    else
      flash[:notice] = 'Os seus locais foram publicados'
    end

    redirect_to seller_account_path
  end

  private

  def load_signin_token
    uuid = params[:signin_token]
    token = SigninToken.get_from_uuid(uuid) if uuid.present?
    @current_signin_token = token

    token.destroy! if token&.expired?

    redirect_to(root_path, alert: 'Link inválido') and return unless token.present?

    if current_seller_user.present? && token.seller_user != current_seller_user
      redirect_to(seller_account_path,
                  alert: "Erro: Já se encontra autenticado como #{current_seller_user.email}")
    else
      seller_user = token.seller_user
      sign_in(:seller_user, seller_user)
    end
  end
end

app/controllers/seller/base_controller.rb
# frozen_string_literal: true
class Seller::BaseController < ApplicationController
  before_action :authenticate_seller_user!

  protected

  def body_class
    "seller-area #{super}"
  end
end

app/controllers/seller/places_controller.rb
# frozen_string_literal: true
class Seller::PlacesController < Seller::BaseController
  before_action :load_place, except: %i[new create]
  before_action :load_locations, only: %i[new edit create update]

  def show
    redirect_to(seller_place_url(@place)) and return if seller_place_url(@place) != request.url
  end

  def new
    redirect_to(seller_account_url) and return unless Flipper.enabled?(:registration)

    @place = current_seller_user.seller.places.build
  end

  def create
    redirect_to(seller_account_url) and return unless Flipper.enabled?(:registration)

    @place = current_seller_user.seller.places.build(place_params)

    if @place.save
      redirect_to seller_place_path(@place), notice: 'Local criado com sucesso, aguarda validação.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to seller_place_path(@place), notice: 'Alterações guardadas com sucesso.'
    else
      render :edit
    end
  end

  def publish
    if @place.can_publish?
      @place.update(published: true, published_at: Time.now)
      redirect_to seller_place_path(@place), notice: 'Este local foi publicado'
    else
      redirect_to seller_place_path(@place), alert: 'Não é possivel publicar este local. Por favor contacte-nos'
    end
  end

  private

  def load_place
    @place = current_seller_user.places.friendly.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :category_id, :district, :area, :address, :main_photo)
  end
end

app/controllers/seller/vouchers_controller.rb
# frozen_string_literal: true
class Seller::VouchersController < Seller::BaseController

  def index
    base_scope = current_seller_user.seller.vouchers.seller_visible
    params[:q].reject! { |_,v| v.blank? } if params[:q].present?
    @q = base_scope.ransack(params[:q])
    @vouchers = params[:q].present? ? @q.result.order(:state) : base_scope.all.order(:state)
  end

  def update
    voucher = Voucher.find(params[:id])
    @form = VoucherRedeemForm.new(redeem_params.merge(voucher: voucher))

    if @form.save
      redirect_to seller_vouchers_path, notice: 'Voucher marcado como usado'
    else
      render :redeem
    end
  end

  def redeem
    voucher = Voucher.find(params[:id])

    @form = VoucherRedeemForm.new(voucher: voucher)
  end

  private

  def redeem_params
    params.require(:voucher_redeem_form).permit(:used_value)
  end
end

app/views/sellers/index.slim
- title "#{@category.name_plural} em #{@city}"
- set_meta_tags og: { title: :full_title, site_name: :site}, twitter: { title: :full_title }

- content_for :header do
  = render 'sellers/header'

section#places-container.xcontainer
  .xrow
    h2.xcol-6.section-separator
      => @sellers.count
      | Resultados

  #places-list.xrow
    == render @sellers

app/views/sellers/show.slim
- title @seller.name
- set_meta_tags og: { title: :full_title, site_name: :site}, twitter: { title: :full_title }
- content_for :header do
  = render 'header'

#place-hero.xcontainer
  - if @show_back
    = link_to '&slarr; Voltar à pesquisa'.html_safe, request.referrer, id:'place-back'
  - else
    = link_to '&slarr; Voltar ao início'.html_safe, root_path, id:'place-back'

  .xrow
    #hero-text.xcol-6
      h1 = @seller.name
      p
        => @seller.category.name
        ' &middot;
        = @seller.address

      = simple_form_for @voucher do |f|
        h3 Apoie este local, seleccione o valor do voucher
        = f.input_field :seller_id, as: :hidden
        = f.input :value, as: :radio_buttons, collection: Seller::DEFAULT_EUR_VALUES, checked: 20, legend_tag: false
        = f.input :custom_value, as: :integer, label: false, placeholder: 'Outro valor', class: 'euro', wrapper_class:'euro', input_html: {min: 1}
        = f.submit 'Comprar voucher'
        = image_tag 'icon-mb-faded.svg', alt: "Multibanco", class: 'voucher-mb'

    = image_tag @seller.main_photo_url(:large, public: true) || 'place-img.jpg', class: 'xcol-5 xoffset-1', id: 'hero-img'

  section#place-share.section
    .xrow
      h2.xcol-6.section-separator Partilhe com os seus amigos, para que possam apoiar também
    .xrow.xcol-6
      / TODO: add this page URL
      iframe allow="encrypted-media" allowtransparency="true" frameborder="0" height="28" scrolling="no" src="https://www.facebook.com/plugins/share_button.php?href=#{seller_url(@seller)}&layout=button_count&size=large&width=110&height=28" style="border:none;overflow:hidden" width="110"
      a.twitter-share-button data-show-count="false" data-size="large" href="https://twitter.com/share?ref_src=twsrc%5Etfw"  Tweet
      script async="" charset="utf-8" src="https://platform.twitter.com/widgets.js"
      .link
        input disabled='true' type="text" value=seller_url(@seller)

  == render 'other_sellers'

  section#kicker.section
    .xrow
      h2.xcol-6.section-separator Pesquise mais locais
    .xrow
      = render 'shared/search_form', locals: {extra_classes: 'xcol-6'}