config/routes.rb
Rails.application.routes.draw do
  # redirect herokuapp (in production only)
  # if Rails.env.production? && !ENV.fetch('HOSTNAME').ends_with?('herokuapp.com')
  #   constraints(host: "#{ENV.fetch('HEROKU_APP_NAME') { 'preserve-prod' }}.herokuapp.com") do
  #     get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
  #     get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  #   end
  # end

  # Partner subdomains
  constraints(->(req){ req.subdomain.present? && Subdomains::Partner.matches?(req) }) do
    get '/', to: 'partners#index'
    get :search, to: 'partners#search', constraints: { format: :js }, as: :partner_search
    get :tos, to: 'partners#tos', as: :partner_tos
    get :faq, to: 'partners#faq', as: :partner_faq

    devise_scope :seller_user do
      get '/comerciante/registo', to: 'seller_users/partner_registrations#new', as: :new_partner_signup
      post '/comerciante', to: 'seller_users/partner_registrations#create', as: :partner_signup
    end

    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  # Other subdomains are redirected
  constraints(->(req){ req.host != ENV['HOSTNAME'] &&
                       req.subdomain.present? &&
                       !req.subdomain.in?(Subdomains::Partner.subdomains)}) do
    get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  ### Fix some shared URLs that are 404s
    get '/Compre', to: redirect('/')
    get '/.', to: redirect('/')
    get '/*', to: redirect('/')
  ###

  constraints(host: ENV['HOSTNAME']) do
    root to: 'home#index'

    resources :places, only: [:index, :show]
    resources :vouchers, only: [:create, :show] do
      resources :payments, only: [:new, :create]

      get '/obrigado', to: 'payments#done', as: :thank_you, on: :member
    end

    get '/tos', to: 'home#tos', as: :tos
    get '/tos_mbway', to: 'home#tos_mbway', as: :tos_mbway
    get '/privacy', to: 'home#privacy', as: :privacy

    # devise_for :seller_users,
    #           path: 'comerciante',
    #           controllers: { registrations: 'seller_users/registrations'},
    #           path_names: { sign_up: 'registo' }

    namespace :seller do
      resource :account, only: [:show] do
        put :accept_new_terms
        get :republish, on: :member
      end
      resources :places, except: [:index, :destroy] do
        patch :publish, on: :member
      end
      resources :vouchers, only: [:index, :update] do
        get :redeem, on: :member
      end
    end

    get '/comerciante/bem-vindo', to: 'places#register_success', as: :register_success

    namespace :webhooks do
      get 'payment/eupago', to:'eu_pago#webhook'
    end

    devise_for :admin_users, path: 'admin'

    namespace :admin do
      resources :admin_users
      resources :categories
      resources :csv_imports, except: [:edit, :update]
      resources :payment_notifications, only: [:index, :show]
      resources :sellers
      resources :partners
      resources :partnerships
      resources :partner_identifiers, only: [:index, :show]
      resources :places do
        member do
          patch :publish
          patch :unpublish
        end
      end
      resources :seller_users
      resources :vouchers do
        patch :resend, on: :member
        patch :mark_refunded, on: :member
      end

      get 'stats', to: 'stats#index', as: :stats
      get 'stats/vouchers', to: 'stats#vouchers', as: :voucher_stats
      get 'stats/sellers', to: 'stats#sellers', as: :seller_stats
      root to: "stats#index"
    end
  end

  authenticate :admin_user do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/models/place.rb
# frozen_string_literal: true
class Place < ApplicationRecord
  DEFAULT_EUR_VALUES = [20, 30, 40, 50].map { |v| ["€#{v}", v] }

  extend FriendlyId
  friendly_id :slug_candidates, use: %i[history]

  include PhotoUploader::Attachment.new(:main_photo)
  belongs_to :category
  belongs_to :seller
  has_many :vouchers, dependent: :restrict_with_exception

  has_one :partnership, inverse_of: :place, dependent: :destroy
  has_one :partner, through: :partnership, inverse_of: :places
  has_one :partner_identifier, through: :partnership

  validates :name, :area, :address, :main_photo, presence: true
  validate  :seller_has_api_key

  scope :sorted, -> { order(name: :asc) }
  scope :published, -> { where(published: true) }
  scope :ever_published, -> { where.not(published_at: nil) }

  default_scope -> { includes(:partnership, :partner, :category) }

  paginates_per 30

  attr_writer :district

  def district
    @district ||= Location.find_by(area: area)&.district
  end

  def can_publish?
    !published && seller&.payment_api_key&.present? && main_photo.present?
  end

  def photo_url(size)
    # fallback to original to handle the gap between upload
    # and derivative generation
    main_photo_url(size, public: true) || main_photo_url(public: true)
  end

  attr_reader :partner_id

  def partner_id=(value)
    self.partner = Partner.find_by_id(value)
  end

  def approved_partner
    partner if partnership&.approved?
  end

  def active_partner
    approved_partner if approved_partner&.active? && !partnership.limit_reached?
  end

  def promo_limit_reached?
    approved_partner.try(:voucher_limit).present? &&
    approved_partner.voucher_limit.positive? &&
    vouchers.total_paid.where(partner: approved_partner).count >= approved_partner.voucher_limit
  end

  def to_s
    "Place ##{id}: #{name}"
  end

  private

  def slug_candidates
    [
      :name,
      %i[name area],
      %i[name area id]
    ]
  end

  def seller_has_api_key
    errors.add(:base, 'Seller must have API key') if published? && seller.payment_api_key.blank?
  end

  def should_generate_new_friendly_id?
    slug.blank? || name_changed?
  end
end

app/controllers/admin/places_controller.rb
# frozen_string_literal: true
module Admin
  class PlacesController < Admin::ResourcefulController
    before_action :find_place, only: %i[publish unpublish]
    before_action :load_locations, only: %i[new edit create update]

    def index_columns
      [
        { attr: :id, label: 'ID', sort: :id },
        { attr: :name, label: 'Name', sort: :name },
        { attr: :category, label: 'Category', sort: nil, formatter: ->(view, place) { view.link_to place.category.name, [:admin, place.category] }  },
        { attr: :area, label: 'Area', sort: :area },
        { attr: :published, label: 'Published', sort: :published },
        { attr: :created_at, label: 'Created At', sort: :created_at },
        { attr: :updated_at, label: 'Updated At', sort: :updated_at }
      ]
    end

    def publish
      authorize! :publish, @resource

      if @resource.can_publish?

        if @resource.published_at.nil?
          ApplicationMailer.seller_place_published_notification(@resource.id).deliver_later
        end
        @resource.update(published: true, published_at: Time.now)

      else
        flash[:alert] = "Can't publish. Place needs photo and payment API key"
      end
      redirect_to [:admin, @resource], notice: 'Place was published'
    end

    def unpublish
      authorize! :unpublish, @resource
      @resource.update(published: false)
      redirect_to [:admin, @resource], notice: 'Place was unpublished'
    end

    def find_resource(slug)
      @resource = Place.friendly.find(slug)
    end

    def find_place
      @resource = Place.friendly.find(params[:id])
    end

    protected

    def permitted_params
      super.permit!
    end

    private

    def load_locations
      gon.locations = Location.grouped_areas
    end
  end
end

app/controllers/places_controller.rb
# frozen_string_literal: true
class PlacesController < ApplicationController
  before_action :load_place_and_ensure_canonical_url, only: [:show]

  def index
    redirect_to(root_url) and return unless Flipper.enabled?(:selling)

    @city = params[:city]

    search = PlaceSearch.new(category: params[:category], city: @city, page: params[:page])

    @category = search.category
    @places = search.places
    @title = search.title
  end

  def show
    @city = @place.area
    @category = @place.category
    @voucher = @place.vouchers.new
    @other_places = OtherPlacesQuery.for_place(@place)

    @show_back = request.referer.present? && URI.parse(request.referer).path == places_path
  end

  # temporary page for seller registration success
  # until we have a seller login area
  def register_success
  end

  private

  def load_place_and_ensure_canonical_url
    redirect_to(root_url) and return unless Flipper.enabled?(:selling)

    @place = Place.published.includes([:category]).friendly.find(params[:id])
    redirect_to(place_url(@place)) and return if place_url(@place) != request.url
  end
end

app/controllers/seller/places_controller.rb
# frozen_string_literal: true
class Seller::PlacesController < Seller::BaseController
  before_action :load_place, except: %i[new create]
  before_action :load_locations, only: %i[new edit create update]

  def show
    redirect_to(seller_place_url(@place)) and return if seller_place_url(@place) != request.url
  end

  def new
    redirect_to(seller_account_url) and return unless Flipper.enabled?(:registration)

    @place = current_seller_user.seller.places.build
  end

  def create
    redirect_to(seller_account_url) and return unless Flipper.enabled?(:registration)

    @place = current_seller_user.seller.places.build(place_params)

    if @place.save
      redirect_to seller_place_path(@place), notice: 'Local criado com sucesso, aguarda validação.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @place.update(place_params)
      redirect_to seller_place_path(@place), notice: 'Alterações guardadas com sucesso.'
    else
      render :edit
    end
  end

  def publish
    if @place.can_publish?
      @place.update(published: true, published_at: Time.now)
      redirect_to seller_place_path(@place), notice: 'Este local foi publicado'
    else
      redirect_to seller_place_path(@place), alert: 'Não é possivel publicar este local. Por favor contacte-nos'
    end
  end

  private

  def load_place
    @place = current_seller_user.places.friendly.find(params[:id])
  end

  def place_params
    params.require(:place).permit(:name, :category_id, :district, :area, :address, :main_photo)
  end
end

app/views/admin/places/_form_fields.html.slim
= f.input :name
= f.association :category
= f.association :seller
= f.input :district, collection: Location.all_districts, input_html:{ id: 'district_select'}
= f.input :area, collection: Location.for_district(f.object.district).map(&:area), selected: f.object.area, input_html:{ id: 'area_select'}
= f.input :address
= f.input :slug
= f.input :main_photo, validate: false
= f.hidden_field :main_photo, value: f.object.cached_main_photo_data, id:nil

app/views/admin/places/_search_filters.slim
.form-row.mb-2
  = f.input :name_cont, label: 'Name', as: :string, wrapper_class: 'col'
  = f.input :category_id_eq, label: 'Category', as: :select, wrapper_class: 'col', collection: Category.all
.form-row.mb-2
  = f.input :area_cont, label: 'Area', as: :string, wrapper_class: 'col'
  = f.input :published_eq, label: 'Published', as: :select, wrapper_class: 'col', collection: [['Yes', true],['No', false]]

app/views/admin/places/_show_content.slim
- content_for :resource_actions do
  - if @resource.partnership.present? && can?(:edit, @resource.partnership)
    = link_to 'Edit partnership', edit_admin_partnership_path(@resource.partnership), class: 'btn btn-outline-primary btn-sm'
  - elsif !@resource.partnership.present? && can?(:create, Partnership)
    = link_to 'Add partnership', new_admin_partnership_path(place_id: @resource.id), class: 'btn btn-outline-primary btn-sm'
  - if can? :publish, @resource
    = button_to 'Publish', publish_admin_place_path(@resource), class: "btn btn-outline-primary btn-sm", method: :patch
  - if can? :unpublish, @resource
    = button_to 'Unpublish', unpublish_admin_place_path(@resource), class: "btn btn-warning btn-sm", method: :patch

- content_for :show_content
  table.table.table-hover
    tbody
      tr
        td
          strong Photo
        td
          - if @resource.main_photo.present?
            = image_tag @resource.photo_url(:small)
          br
          => link_to 'Small photo', @resource.main_photo_url(:small, public: true), target: '_blank'
          ' |
          = link_to 'Large photo', @resource.main_photo_url(:large, public: true), target: '_blank'
      tr
        td
          strong ID
        td
          = @resource.id
      tr
        td
          strong Name
        td
          = @resource.name
      tr
        td
          strong Published
        td
          = @resource.published
      tr
        td
          strong Published At
        td
          = @resource.published_at
      tr
        td
          strong Seller
        td
          = link_to @resource.seller, [:admin, @resource.seller]
      tr
        td
          strong Slug
        td
          = @resource.slug
      tr
        td
          strong Category
        td
          = @resource.category.name
      tr
        td
          strong Area
        td
          = @resource.area
      tr
        td
          strong Address
        td
          = @resource.address
      tr
        td
          strong Partnership
        td
          = link_to(@resource.partnership, [:admin, @resource.partnership]) if @resource.partnership.present?
      tr
        td
          strong Total insured amount
        td
          = number_to_currency @resource.vouchers.with_insurance.sum(:value), locale: :pt, precision: 0
      tr
        td
          strong Created At
        td
          = @resource.created_at
      tr
        td
          strong Updated At
        td
          = @resource.updated_at


  h3.mt-4.mb-2 Vouchers

  table.table.table-hover.table-striped
    thead
      th
      th ID
      th Email
      th Value
      th State
      th Created At

    tbody
      - @resource.vouchers.each do |voucher|
        tr
          td
            = link_to 'View', [:admin, voucher]
          td
            = voucher.id
          td
            = voucher.email
          td
            = number_to_currency voucher.value, locale: :pt, precision: 0
          td
            = voucher.state
          td
            = voucher.created_at