config/routes.rb
Rails.application.routes.draw do
  # redirect herokuapp (in production only)
  # if Rails.env.production? && !ENV.fetch('HOSTNAME').ends_with?('herokuapp.com')
  #   constraints(host: "#{ENV.fetch('HEROKU_APP_NAME') { 'preserve-prod' }}.herokuapp.com") do
  #     get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
  #     get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  #   end
  # end

  # Partner subdomains
  constraints(->(req){ req.subdomain.present? && Subdomains::Partner.matches?(req) }) do
    get '/', to: 'partners#index'
    get :search, to: 'partners#search', constraints: { format: :js }, as: :partner_search
    get :tos, to: 'partners#tos', as: :partner_tos
    get :faq, to: 'partners#faq', as: :partner_faq

    devise_scope :seller_user do
      get '/comerciante/registo', to: 'seller_users/partner_registrations#new', as: :new_partner_signup
      post '/comerciante', to: 'seller_users/partner_registrations#create', as: :partner_signup
    end

    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  # Other subdomains are redirected
  constraints(->(req){ req.host != ENV['HOSTNAME'] &&
                       req.subdomain.present? &&
                       !req.subdomain.in?(Subdomains::Partner.subdomains)}) do
    get '/', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}")
    get '*path', to: redirect("https://#{ENV.fetch('HOSTNAME') { 'preserve.pt' }}/%{path}")
  end

  ### Fix some shared URLs that are 404s
    get '/Compre', to: redirect('/')
    get '/.', to: redirect('/')
    get '/*', to: redirect('/')
  ###

  constraints(host: ENV['HOSTNAME']) do
    root to: 'home#index'

    resources :places, only: [:index, :show]
    resources :vouchers, only: [:create, :show] do
      resources :payments, only: [:new, :create]

      get '/obrigado', to: 'payments#done', as: :thank_you, on: :member
    end

    get '/tos', to: 'home#tos', as: :tos
    get '/tos_mbway', to: 'home#tos_mbway', as: :tos_mbway
    get '/privacy', to: 'home#privacy', as: :privacy

    # devise_for :seller_users,
    #           path: 'comerciante',
    #           controllers: { registrations: 'seller_users/registrations'},
    #           path_names: { sign_up: 'registo' }

    namespace :seller do
      resource :account, only: [:show] do
        put :accept_new_terms
        get :republish, on: :member
      end
      resources :places, except: [:index, :destroy] do
        patch :publish, on: :member
      end
      resources :vouchers, only: [:index, :update] do
        get :redeem, on: :member
      end
    end

    get '/comerciante/bem-vindo', to: 'places#register_success', as: :register_success

    namespace :webhooks do
      get 'payment/eupago', to:'eu_pago#webhook'
    end

    devise_for :admin_users, path: 'admin'

    namespace :admin do
      resources :admin_users
      resources :categories
      resources :csv_imports, except: [:edit, :update]
      resources :payment_notifications, only: [:index, :show]
      resources :sellers
      resources :partners
      resources :partnerships
      resources :partner_identifiers, only: [:index, :show]
      resources :places do
        member do
          patch :publish
          patch :unpublish
        end
      end
      resources :seller_users
      resources :vouchers do
        patch :resend, on: :member
        patch :mark_refunded, on: :member
      end

      get 'stats', to: 'stats#index', as: :stats
      get 'stats/vouchers', to: 'stats#vouchers', as: :voucher_stats
      get 'stats/sellers', to: 'stats#sellers', as: :seller_stats
      root to: "stats#index"
    end
  end

  authenticate :admin_user do
    require 'sidekiq/web'
    require 'sidekiq/cron/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    mount Flipper::UI.app(Flipper) => '/admin/flipper'
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true
class HomeController < ApplicationController
  before_action :set_location

  def index
    if Flipper.enabled?(:selling)
      @spinner_categories = %w[Restaurante Café Cabeleireiro Museu Teatro]
      @places = Place.published.includes(:category).order('RANDOM()').limit(4)
    end

    @stats_cache = [Place.published.maximum(:updated_at), Voucher.for_stats.maximum(:payment_completed_at)]
  end

  def tos
  end

  def tos_mbway
  end

  def privacy
  end

  def privacy
  end
end

app/views/home/index.slim
- content_for :header do
  = render 'shared/header'


- set_meta_tags title: nil,
                og: { title: 'Preserve os seus locais preferidos', site_name: :site},
                twitter: { title: 'Preserve os seus locais preferidos' }

.container-xl
  section#hero
    .row
      .col-md-7.col-lg-7.col-12
        .hero-text
          - if Flipper.enabled?(:selling)
            h1.hero-wrapper
              | Preserve o seu
              br
              .hero-ticker
                - @spinner_categories.each do |c|
                  span = c
              br
              | favorito
            p Compre um voucher para usar em qualquer altura, e ajude a sua economia local a sobreviver ao COVID-19
            = render 'shared/search_form'
          - else
            h1.hero-wrapper Obrigado a todos
            p Devido ao Covid-19, todo o comércio local teve que fechar a portas, criando grandes dificuldades financeiras aos mesmos. A Preserve nasceu para ajudar estes locais, dando a possibilidade a estes de venderem vouchers aos seus clientes, gerando receitas imediatas.
            p Estamos profundamente agradecidos pela adesão em massa a esta iniciativa. Devido ao grande apoio do público, milhares de negócios reabriram as portas após o estado de emergência.
            p Obrigado.

      .col-md-5.col-lg-5.d-none.d-md-block
        = image_tag 'hero-img.jpg', alt:'Pessoa', class:'hero-img'
    .row
      .col-md-8.col-12
        - cache @stats_cache do
          section.hero-stats.clearfix
            article.stat
              h2 = Place.ever_published.count
              p Locais
            article.stat
              h2 = Voucher.for_stats.count
              p Vouchers vendidos
            article.stat
              h2 = number_to_currency Voucher.for_stats.sum(:value), locale: :pt, precision: 0
              p Angariados
  - cache [:how_it_works, ENV['HEROKU_SLUG_COMMIT']] do
    section#how-it-works.section
      #how-it-works-brief.row
        .col-12.col-md-6
          - if Flipper.enabled?(:selling)
            h2.section-separator Os seus locais preferidos precisam de ajuda
            p Por causa do Covid-19, os seus locais preferidos estão de portas fechadas. A maioria não vai aguentar mais de 1-2 meses sem clientes e vão ter de tomar decisões drásticas, como despedir o pessoal, ou abrir falência.
            p Pode ajudar.
          - else
            h2.section-separator Como funcionava a Preserve?
            p Por causa do Covid-19, os seus locais preferidos estiveram de portas fechadas. A maioria não conseguiria aguentar mais de 1-2 meses sem clientes e tiveram de tomar decisões drásticas, como despedir o pessoal, ou abrir falência.
            p Devido ao seu apoio, muitos deles conseguiram reabrir as portas.
        .col-md-6.d-none.d-md-block
          = image_tag 'help.svg', alt: 'Hug'

    #how-it-works-facts.row
      .col-sm-4.col-12.fact
        = image_tag 'icon-voucher.svg', alt: 'Voucher'
        h3 Compre um voucher para usar no futuro
        p Os vouchers são válidos durante 24 meses e podem ser utilizados em qualquer altura.
      .col-sm-4.col-12.fact
        = image_tag 'icon-money.svg', alt: 'Money'
        h3 O local recebe o dinheiro imediatamente
        p O dinheiro é transferido diretamente de si para a conta do local. Todos os pagamentos estão protegidos contra fraude e todos os locais foram verificados manualmente.
      .col-sm-4.col-12.fact
        = image_tag 'icon-heart.svg', alt: 'Heart'
        h3 Parabéns, contribuiu para sua economia local!
        p Contribuiu para que os seus sítios preferidos sobrevivam e consigam pôr comida na mesa das suas famílias.

  - if Flipper.enabled?(:selling)
    - cache @places do
      section.places-container.section
        .row
          h2.col-12.section-separator Quem recebe o seu apoio

        .places-list.row.home-list
          == render @places

  - cache [:homepage_bottom, ENV['HEROKU_SLUG_COMMIT']] do
    section#press.section
      .row
        h2.col-12.section-separator Como visto em
      .press-wrapper.row
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-acb.png', alt: 'ACB'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-madeoflisboa.png', alt: 'Made of Lisboa'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-acsjm.png', alt: 'ACSJM'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-acde.png', alt: 'ACDE'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-eg.png', alt: 'E-Gosto'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-rdp.png', alt: 'RDP'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-acif.png', alt: 'ACIF'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-provar.png', alt: 'Provar'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-aevc.png', alt: 'AEVC'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-aicc.png', alt: 'AICC'
        .col-4.col-lg-2
          .press-logo
            = image_tag 'partners/press-cmf.png', alt: 'CMF'

    - if Flipper.enabled?(:registration)
      section#businesses.section
        .row
          .col-12.col-md-8.col-lg-6
            h2.section-separator Tem um estabelecimento? Comece a vender vouchers hoje.
            = link_to 'Submeta o seu local', new_seller_user_registration_path, class: 'primary-cta'


  - if Flipper.enabled?(:selling)
    section#kicker.section
      .row
        .col-12.col-md-8.col-lg-6
          h2.section-separator
            ' Está à espera de quê?
            br
            | Preserve o seu sítio preferido agora
          = render 'shared/search_form'

app/views/home/privacy.slim
- content_for :header do
  = render 'shared/header'

.container-xl.content
  .row
    .col-12.col-xl-8.offset-xl-2
      markdown:
        # Política de Privacidade, Proteção de Dados e Cookies
        A Preserve agradece a sua visita ao nosso website. Para nós é muito importante garantir a privacidade, segurança e proteção dos seus dados pessoais, tanto no processo de recolha como no tratamento dos mesmos.

        Neste sentido, criamos a presente política de privacidade e proteção de dados, com vista a explicar que informações são recolhidas pela Preserve quando visita/utiliza o nosso website e de que forma estas informações são utilizadas.

        ### Quem somos?
        O Tech4Covid19 é um movimento que reúne pessoas e empresas ligadas ao setor tecnológico e que tem como missão desenvolver, de forma aberta e colaborativa, soluções para combater o impacto do novo coronavirus (Covid19) através da tecnologia.

        Os seus dados pessoais serão tratados pela equipa voluntária do movimento Tech4Covid19 responsável pela gestão da plataforma Preserve.

        As pessoas singulares acima identificadas assumem a qualidade de Responsáveis Conjuntas pelo Tratamento dos seus dados pessoais, nos termos e de acordo com o disposto no Regulamento Geral sobre a Proteção de Dados – o Regulamento (EU) 2016/679 do Parlamento Europeu e do Conselho de 27 de abril de 2016 (“RGPD”).

        Dados pessoais são informações específicas sobre características pessoais ou factuais relacionadas com um indivíduo que pode ser identificado a partir desses dados. Isso inclui informações como o nome, morada, número de telefone e data de nascimento. As informações que não permitem a sua identificação ou que não podem ser diretamente ligadas à sua identidade não são consideradas dados pessoais.

        ### Que dados pessoais são recolhidos e tratados?
        Pode navegar no nosso website sem nos disponibilizar quaisquer dados pessoais.

        Apenas são recolhidos os seus dados no caso de se registar como Parceiro, ou na compra de um voucher.

        ### Os meus dados pessoais serão partilhados com terceiros?
        Os seus dados pessoais poderão ser partilhados com terceiros, mais concretamente prestadores de serviços individuais ou similares, nomeadamente, para o alojamento do website e correio eletrónico, ou para o prestador de serviços de pagamento, a Eupago, ou para seguradoras e mediadores associados, nomeadamente a Ageas Portugal, Companhia de Seguros SA e a Keep Warranty Lda., respetivamente, ou para motivos de verificação de legitimidade com parceiros, nomeadamente a L'Oreal Divisão Produtos Profissionais e Super Bock Bebidas, S.A. Apenas serão partilhados os dados necessários para a prestação dos serviços em causa, nomeadamente, email, valor do voucher comprado, retalhista, morada do retalhista, distribuidor ou número de cliente com os terceiros mencionados e data de compra do voucher.
        
        Apenas serão partilhados os dados necessários para a prestação dos serviços em causa. Os seus dados serão tratados apenas dentro do Espaço da União Europeia.

        ### Quais são os seus direitos?
        Nos termos da legislação sobre proteção de dados pessoais, garantimos-lhe o direito de acesso, obtenção de cópia dos dados pessoais que a Preserve disponha sobre si, atualização, retificação, eliminação, portabilidade e apagamento dos seus dados pessoais. Assiste-lhe ainda o direito de apresentar reclamações perante a Comissão Nacional de Proteção de Dados (CNPD).

        ### O que são cookies?
        Cookies são pequenas etiquetas de software que são armazenadas no seu computador ou outros dispositivos que utiliza para aceder à internet, através do navegador (browser). Saiba mais sobre cookies em: allaboutcookies.org.

        ### Qual a finalidade dos cookies?
        A utilização de cookies tem o objetivo de melhorar a experiência de navegação do utilizador, aumentando a rapidez e eficiência de resposta dos websites. Elimina a necessidade de introduzir repetidamente as mesmas informações e ajudam a determinar a utilidade, interesse e o número de utilizações. Cada cookie tem uma função e uma data de validade. A Preserve não utilizará, sem consentimento prévio, dados armazenados em cookies nos casos em que tal seja exigido.

        ### Que cookies são usados no website?
        Este site utiliza cookies proprietários e de terceiros. Os cookies de terceiros diferem dos primeiros na medida em que são enviados para o dispositivo do utilizador, a partir de um equipamento ou domínio, que não se encontra sob o controlo ou gestão direta da Preserve.

        Os cookies podem ser classificados da seguinte forma:

        Cookies essenciais - São fundamentais para aceder a áreas específicas do website. Permitem a navegação no website e a utilização das suas aplicações, tal como o acesso a áreas seguras através de login. Estes cookies não recolhem informação sobre o utilizador que possa ser utilizada para fins de marketing ou para identificar as visitas do utilizador a websites. Sem eles, certos serviços não podem ser prestados.

        Cookies analíticos - Permitem analisar a forma como os utilizadores usam o website, permitindo destacar artigos ou serviços que podem ser do seu interesse, monitorizar o desempenho do mesmo, conhecendo quais as páginas mais populares. Estes cookies são utilizados apenas para efeitos de criação e análise estatística.

        Cookies funcionais - Permitem relembrar as preferências do utilizador relativamente à navegação no website. Assim, o utilizador não necessita de o reconfigurar e personalizar cada vez que o visita.

        ### Ligações a sites de terceiros
        O Preserve possui ligações para outros sites, os quais, a nosso ver, podem conter informações / ferramentas úteis para os nossos visitantes. A nossa política de privacidade não é aplicada a sites de terceiros, pelo que, caso visite outro site a partir do nosso deverá ler a política de privacidade do mesmo.

        Não nos responsabilizamos pela política de privacidade ou conteúdo presente nesses mesmos sites.

        ### Alterações a esta política
        A equipa do Preserve reserva-se ao direito de alterar este acordo sem aviso prévio. Deste modo, recomendamos que consulte a nossa política de privacidade com regularidade de forma a estar sempre atualizado.

        O exercício destes direitos deverá ser realizado através do seguinte endereço de correio eletrónico [info@preserve.pt](info@preserve.pt)

app/views/home/tos_mbway.slim
- content_for :header do
  = render 'shared/header'

.container-xl.content
  .row
    .col-12.col-xl-8.offset-xl-2
      markdown:
        # Termos e Condições da campanha MB WAY & Preserve.pt

        ## I. Definições

        1. Campanha "CAMPANHA MB WAY & PRESERVE.PT": denominação da campanha das marcas SIBS e Preserve.pt.

        2. Participante: Todos os utilizadores MB WAY. A SIBS reserva o direito de verificar a elegibilidade dos participantes e pedir para que os mesmos se identifiquem, de forma a garantir a veracidade da participação.

        3. Promotora: SIBS Forward Payment Solutions, com sede na Rua Soeiro Pereira Gomes Lote nº 1 – 1649 – 031 Lisboa, registada com o número único de pessoa coletiva 505107546, na Conservatória do Registo Comercial de Lisboa, doravante "SIBS".

        4. Prazo de Duração: A Campanha CAMPANHA MB WAY & PRESERVE.PT” estará ativa de 30 de abril de 2020 a 14 de junho de 2020.

        ## II. PARTICIPAÇÃO

        1. Durante o período compreendido entre as 00h00 do dia 30 de abril de 2020 e as 23h59 do dia 14 de junho de 2020, compre o seu voucher no valor igual ou superior a 20€ com MB WAY e o MB WAY oferece-lhe 2€ extra em voucher e o valor também é ressarcido aos estabelecimentos aderentes à iniciativa. A compra tem que ser realizada através do site [preserve.pt](https://preserve.pt/). O horário é referente a Portugal Continental.

        2. Apenas as compras MB WAY através da operativa do número de telemóvel são válidas para a campanha. As compras com cartões MB NET estão excluídas da campanha.

        ## III. OFERTA

        1. O valor extra é parametrizado antes do pagamento da compra, pelo que o cliente paga o valor que iria pagar inicialmente.

        2. O valor extra é válido para compras iguais ou superiores a 20€, em [preserve.pt](https://preserve.pt/), até um valor máximo de 200€.

        3. Os vouchers poderão ser redimidos até 24 meses após a respetiva emissão.

        4. A campanha está limitada às primeiras 2500 compras MB WAY válidas no âmbito da campanha, de acordo com os presentes Termos e Condições.

        5. Caso o estabelecimento escolhido pelo Consumidor não reabra (de forma provisória ou permanente, qualquer que seja o motivo subjacente) antes do utilizador efetuar a redenção do vale adquirido, o MB WAY e a Preserve não terão qualquer responsabilidade pela infeliz situação, sendo um risco que o Consumidor, bem como o MB WAY está disposto a correr ao adquirir os vouchers.

        6. O utilizador poderá exercer o direito de resolução e cancelamento de qualquer voucher adquirido sem que lhe seja exigida qualquer indemnização, no prazo de 14 (catorze) dias a contar da data de receção do voucher. No caso do voucher adquirido consistir num voucher alvo de valor extra de 2€ adicionais pelo MB WAY, segundo os critérios estabelecidos acima nos presentes Termos e Condições, apenas o valor pago pelo utilizador será alvo de reembolso.

        ## IV. PROCESSO DE REDENÇÃO

        1. Após cada pagamento efetuado com sucesso, o utilizador receberá o seu voucher via e-mail, juntamente com um comprovativo de pagamento.

        2. O utilizador deverá dirigir-se ao estabelecimento escolhido e apresentar o seu comprovativo digital para redimir o voucher.

        3. Os vouchers apresentados no estabelecimento escolhido serão validados pelo responsável do estabelecimento, que procederá à entrega de produto/serviço equivalente ao valor do voucher entregue.


        ## V. OUTRAS CONDIÇÕES

        1. A SIBS reserva-se o direito de suspender parcial ou definitivamente a participação de participantes que incumpram qualquer das disposições constantes dos presentes Termos e Condições ou que considere terem revelado um comportamento inadequado a viabilizar a manutenção da sua participação na campanha. Neste caso, o participante não terá direito à correspondente devolução.

        2. A SIBS não se responsabiliza por qualquer prejuízo/alteração das condições à viagem ou o cancelamento da mesma.

        3. A SIBS é alheia à tipologia de negócio do parceiro onde a campanha é comunicada e qualquer limitação no parceiro é da responsabilidade do mesmo.

        4. A Preserve e a SIBS não são responsáveis, nem têm controlo, nem prestam qualquer garantia sobre a prestação dos serviços prestados pelos estabelecimentos aderentes à iniciativa, bem como sobre a qualidade, pontualidade ou qualquer outro aspeto relacionado com aqueles.

        5. Caso exista motivo atendível, a SIBS poderá introduzir, a qualquer momento, alterações a estes Termos e Condições, as quais serão efetivas após a sua divulgação com publicação em [www.mbway.pt](https://www.mbway.pt).

        6. Qualquer pedido de esclarecimento adicional sobre a presente campanha deverá ser apresentado por escrito para o e-mail [mbway@sibs.pt](mailto:mbway@sibs.pt)